import Head from 'next/head'
import Image from 'next/image'
import Header from './components/Header/Header'
import Sidemenu from './components/Sidemenu/Sidemenu'
import '/styles/Home.module.css'
import OverView from './components/Sidemenu/dashboard/overview/OverView'


const inter = ({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
    
      <Head>
        <title>webpage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className=''>
   
         <OverView/>
      </main>
    </div>
  )
}
